spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

app:
  jwt:
    secret: dGFza21hbmFnZXJzZWNyZXRrZXkyMDI0YXV0aGVudGljYXRpb25qd3R0b2tlbg==
    expiration: 86400000  # 24h in ms

cors:
  allowed-origins: http://localhost:3000

gemini:
    api:
      key: ${GEM_KEY}
